CREATE TABLE FACTORIAL_RESULTADOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO NUMBER NOT NULL,
    FACTORIAL NUMBER NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE
); 

COMMIT;